### ISSUE TITLE
[Swift] - Assignment 1

### ISSUE THREAD

**Issue by giaotuancse** [giaotuancse/RottenTomato#1]
I've completed assignment 1 Hi, /cc @chug2k
Please review, more optional will be add later. But most of requires and optionals are there. Thank you ;)

**Comment by coderschoolreview** [comment]
I cannot build your project. Please fix it asap.
<img width="1019" alt="screen shot 2015-11-17 at 9 29 08 pm" src="https://cloud.githubusercontent.com/assets/15702670/11214180/5dc204d6-8d72-11e5-8fa9-29a94c243830.png">

**Comment by coderschoolreview** [comment]
So sorry. That syntax is only available in Xcode 7.1. I'm using Xcode 7.0.1. Don't need to fix it :smile:

**Comment by coderschoolreview** [comment]
Hi @giaotuancse 

We still can't compile your project because of a missing `ic_movie_2.png` file. Can you please drop it into your project and commit? The best way is to drag and drop the image into `Assets.xcassets` in your project drawer.

<img width="566" alt="screen_shot_2015-11-18_at_2_14_14_am" src="https://cloud.githubusercontent.com/assets/15702670/11221940/56693ac4-8d9a-11e5-9eef-f624aceddce5.png">

**Comment by giaotuancse** [comment]
Hi @coderschoolreview 
Sorry about this mistake.
I just updated the resources, please update source code. 
Thank you for your suggestion about move icon resources into `Assets.xcassets` ;)

**Comment by coderschoolreview** [comment]
Thanks! We'll try to review it this afternoon.

**Comment by coderschoolreview** [comment]
:+1: nice work. The point of this homework was to explore a simple example of a full MVC application with a RESTful API. You learned about UITableViews, custom UITableViewCells, navigation from a UITableView, and basic networking.

## Grading Summary:
- **Functionality**: Good
- **Code Style**: Needs Improvement
- **Visual Design**: Excellent
- **Usability**: Good
- **Overall**: Good

## Detailed Notes
- Code is so-so with cleanliness. Violating a few rules from the style guide - namely still using semicolons `;`, unnecessary use of `self`, and extra parentheses with `if expr`
  - [Ray Wenderlich Swift Style Guide](https://github.com/raywenderlich/swift-style-guide)
- In future homework, we will cover how to implement models that can deserialize from an NSDictionary. [SwiftyJSON](https://github.com/SwiftyJSON/SwiftyJSON) is a useful project for making it easier to deserialize the JSON response. For a more robust solution, you can also investigate using an ORM like [Pistachio](https://github.com/felixjendrusch/Pistachio).  
- Your custom Movie cell should have a property called `movie`. In the custom setter of `movie`, you should configure the various labels and images. This decouples your custom cells from the table view controllers.
- Nice work loading the images asynchronously.
- Nice work setting up the proper modes for the images so that they are not stretched.
- Note that your images are stretched. You should observe the UIContentMode of the UIImageView. By default, it will stretch the image to match your dimensions, which is probably not what you want.
- Your error message should be displayed if a network request fails and hidden again if it succeeds - do this in the `guard` clause of fecthMovie.

### In the Movie Detail View, can the user scroll to see the whole text?
- Nice job with Movie Details! It took me a while to figure out how to trigger the animation. Can you think of a way to make it easier for the user to know to tap to grow the field?
- Keep alignment in mind when designing a mobile app. Alignment makes a design more neat and organized so that it's easier to read or use. This means that readers will find what they want without frustration  For more information about grid theory, you can read [the article here](http://www.creativebloq.com/web-design/grid-theory-41411345). 
  
  > To use alignment properly, imagine there are evenly-spaced vertical lines running through the entire length of the design. Both the left and right edges of every single item should fall along these lines, which designers call a grid.
  > 
  > You want to align as many items as possible along the same grid lines. Instead of looking at layout like the game Tetris, where the goal is to fill every available space, try to arrange elements in neat columns.

Here, on the movie details, the PG-13 Movie Rating looks a little out of place in both the X and Y directions:
![image](https://cloud.githubusercontent.com/assets/15702670/11234606/3c1e70a0-8dfc-11e5-9c07-905ceb887e5f.png)

![alignment](http://i.imgur.com/Nv3QunL.png)
- Looks like you didn't finish implementing the tab bar. That's okay, it's a good start. 
- I do like the custom Movie Rating Label. It's great to use contrast to have different elements of an app stand out. 

Great job dedicating enough time to do the homework. You learned a lot! Keep up the good work.

**Comment by giaotuancse** [comment]
Thank you for your review and sorry for lately response :smile: 
I will pay attention in coding style in future assignment. Thank you :wink:
